#!/usr/bin/env python3
"""
verify_token_truth.py - Diagnostic and Ground Truth Verification Harness for cuv.

Compares:
  1. Raw JSONL Ground Truth (reading per-turn TUR usage or TC last_token_usage)
  2. `cuv` internal parser (UsageEvents generated by parse_session_file)
  3. `ccusage` external CLI output (if installed)

Usage:
  uv run python verify_token_truth.py --day 2026-09-15
  uv run python verify_token_truth.py --since 2026-09-11 --until 2026-09-16
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import NamedTuple

from codex_usage import (
    AZURE_GPT54_EU_LONG_RATES,
    AZURE_GPT54_EU_STD_RATES,
    collect_events,
    list_session_files,
    parse_session_file,
    load_session_index,
)


class DayStats(NamedTuple):
    uncached_input: int
    cached_input: int
    output: int
    total: int
    cost_usd: float


def parse_day_from_ts(ts: str | None) -> str | None:
    if not ts:
        return None
    try:
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone()
        return dt.date().isoformat()
    except Exception:
        return None


def calculate_turn_cost(uncached_in: int, cached_in: int, output: int, total_prompt: int) -> float:
    # Azure OpenAI GPT-5.4 Global Standard pricing
    # Context threshold: 272,000 tokens
    if total_prompt > 272_000:
        rates = AZURE_GPT54_EU_LONG_RATES
    else:
        rates = AZURE_GPT54_EU_STD_RATES
    return (uncached_in * rates[0]) + (cached_in * rates[2]) + (output * rates[1])


def extract_raw_ground_truth(root: Path, target_day: str) -> DayStats:
    """Computes exact ground truth from raw JSONL files for a given target day."""
    sessions_dir = root / "sessions"
    archived_dir = root / "archived_sessions"

    files: list[Path] = []
    if sessions_dir.exists():
        files.extend(sessions_dir.rglob("*.jsonl"))
    if archived_dir.exists():
        files.extend(archived_dir.glob("*.jsonl"))

    uncached_tot = 0
    cached_tot = 0
    output_tot = 0
    cost_tot = 0.0

    for path in files:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if "token_usage_record" not in line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue

                if d.get("type") != "token_usage_record":
                    continue

                ts = d.get("timestamp")
                if parse_day_from_ts(ts) != target_day:
                    continue

                payload = d.get("payload") or {}
                usage = payload.get("usage") or {}
                total_prompt = int(usage.get("input_tokens") or 0)
                cached = int(usage.get("cached_input_tokens") or usage.get("cache_read_input_tokens") or 0)
                uncached = max(0, total_prompt - cached)
                out = int(usage.get("output_tokens") or 0)

                uncached_tot += uncached
                cached_tot += cached
                output_tot += out
                cost_tot += calculate_turn_cost(uncached, cached, out, total_prompt)

    total_tokens = uncached_tot + cached_tot + output_tot
    return DayStats(
        uncached_input=uncached_tot,
        cached_input=cached_tot,
        output=output_tot,
        total=total_tokens,
        cost_usd=cost_tot,
    )


def extract_cuv_stats(root: Path, target_day: str) -> DayStats:
    """Runs cuv event collection and aggregates for target_day."""
    d = date.fromisoformat(target_day)
    events, diagnostics = collect_events(root=root, since=d, until=d, with_cost=True)

    uncached_tot = sum(e.input_tokens for e in events if e.day == target_day)
    cached_tot = sum(e.cached_input_tokens for e in events if e.day == target_day)
    output_tot = sum(e.output_tokens for e in events if e.day == target_day)
    cost_tot = sum(e.estimated_cost_usd or 0.0 for e in events if e.day == target_day)
    total_tokens = uncached_tot + cached_tot + output_tot

    return DayStats(
        uncached_input=uncached_tot,
        cached_input=cached_tot,
        output=output_tot,
        total=total_tokens,
        cost_usd=cost_tot,
    )


def extract_ccusage_stats(target_day: str) -> DayStats | None:
    """Extracts stats from ccusage if available."""
    try:
        res = subprocess.run(
            ["ccusage", "codex", "daily", "--since", target_day, "--until", target_day, "--json"],
            capture_output=True,
            text=True,
            check=False,
        )
        if res.returncode != 0:
            return None
        data = json.loads(res.stdout)
        daily_list = data.get("daily", [])
        if not daily_list:
            return DayStats(0, 0, 0, 0, 0.0)
        day_entry = daily_list[0]
        return DayStats(
            uncached_input=int(day_entry.get("inputTokens") or 0),
            cached_input=int(day_entry.get("cacheReadTokens") or 0),
            output=int(day_entry.get("outputTokens") or 0),
            total=int(day_entry.get("totalTokens") or 0),
            cost_usd=float(day_entry.get("costUSD") or 0.0),
        )
    except Exception:
        return None


def main():
    parser = argparse.ArgumentParser(description="Verify cuv token truth")
    parser.add_argument("--day", default="2026-09-15", help="Day to verify (YYYY-MM-DD)")
    parser.add_argument("--root", default=str(Path.home() / ".codex"), help="Codex root dir")
    args = parser.parse_args()

    root = Path(args.root)
    day = args.day

    print(f"=== Running Token Truth Verification for {day} ===")
    ground_truth = extract_raw_ground_truth(root, day)
    cuv_stats = extract_cuv_stats(root, day)
    ccusage_stats = extract_ccusage_stats(day)

    print("\nSource Breakdown:")
    print(f"{'Metric':<20} | {'Raw Ground Truth':<18} | {'cuv CLI':<18} | {'ccusage (ref)':<18}")
    print("-" * 82)
    print(f"{'Uncached Input':<20} | {ground_truth.uncached_input:<18,d} | {cuv_stats.uncached_input:<18,d} | {ccusage_stats.uncached_input if ccusage_stats else 'N/A':<18}")
    print(f"{'Cached Read':<20} | {ground_truth.cached_input:<18,d} | {cuv_stats.cached_input:<18,d} | {ccusage_stats.cached_input if ccusage_stats else 'N/A':<18}")
    print(f"{'Output':<20} | {ground_truth.output:<18,d} | {cuv_stats.output:<18,d} | {ccusage_stats.output if ccusage_stats else 'N/A':<18}")
    print(f"{'Total Tokens':<20} | {ground_truth.total:<18,d} | {cuv_stats.total:<18,d} | {ccusage_stats.total if ccusage_stats else 'N/A':<18}")
    print(f"{'Estimated Cost ($)':<20} | ${ground_truth.cost_usd:<17.2f} | ${cuv_stats.cost_usd:<17.2f} | ${ccusage_stats.cost_usd if ccusage_stats else 0.0:<17.2f}")
    print("-" * 82)

    diff_tokens = abs(cuv_stats.total - ground_truth.total)
    diff_cost = abs(cuv_stats.cost_usd - ground_truth.cost_usd)

    if diff_tokens == 0 and diff_cost < 0.01:
        print("\n✅ SUCCESS: cuv matches Ground Truth to the exact token and cent!")
        sys.exit(0)
    else:
        print(f"\n❌ DIVERGENCE DETECTED: Token diff = {diff_tokens:,}, Cost diff = ${diff_cost:.4f}")
        sys.exit(1)


if __name__ == "__main__":
    main()
